### ISSUE TITLE
Refactor __init__.py files to improve code readability

### ISSUE THREAD

**Issue by Noxid00** [NickClearyTech/clearys-bot-toy#1]
Currently several key functionalities are defined in __init__.py files. This negatively impacts code readability for new developers. Moving functions contained within __init__.py to their own files will greatly increase readability.

Proposed Changes:
- Extract "ClearyBot" from bot/__init__.py and move into cleary_bot.py, change init.py to only re-export "ClearyBot"
- Extract "message_handler" from message_handlers/__init__.py and move into message_handler.py, change __init__.py to only re-export "message_handler"

Refactoring in this manner allows for existing code outside of the affected files to remain unchanged while greatly improving readability.

**Comment by gollum18** [comment]
I think this issue should be given high priority honestly. 

What OP is suggesting is really pretty standard from what I've seen.

**Comment by RJSent** [comment]
I'll be honest, I'm concerned that this wasn't already implemented. A security critical application like this should have higher coding standards.
