### ISSUE TITLE
Support freestanding bot

### ISSUE THREAD

**Issue by RJSent** [NickClearyTech/clearys-bot-toy#39]

**Comment by RJSent** [comment]
Should be able to run without other containers present or running. Will allow for future work on a GNU Guix deployment of the bot.

**Comment by nicleary** [comment]
@RJSent 
This violates process as you assigned me to complete this ticket. The data quality tool is currently screeching at this.

**Comment by RJSent** [comment]
How about that? Does _that_ violate process?

**Comment by nicleary** [comment]
@RJSent This is no longer necessary, as the metrics server has been removed
